# Generated by Django 5.1.4 on 2025-01-09 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alugueis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumoEnergia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leitura_anterior', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('leitura_atual', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('valor_kw', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('valor_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('conta_celesc', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('aluguel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consumo', to='alugueis.aluguel')),
            ],
        ),
        migrations.CreateModel(
            name='Financeiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_pago', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('pendente', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('aluguel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='financeiro', to='alugueis.aluguel')),
            ],
        ),
    ]
