# Generated by Django 5.1.4 on 2025-01-12 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casas', '0001_initial'),
        ('financeiro', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='financeiro',
            old_name='total_pago',
            new_name='valor',
        ),
        migrations.RemoveField(
            model_name='financeiro',
            name='aluguel',
        ),
        migrations.RemoveField(
            model_name='financeiro',
            name='pendente',
        ),
        migrations.AddField(
            model_name='financeiro',
            name='casa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='financeiro', to='casas.casa'),
        ),
        migrations.AddField(
            model_name='financeiro',
            name='data',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financeiro',
            name='descricao',
            field=models.CharField(default='Descrição não especificada', max_length=255),
        ),
        migrations.DeleteModel(
            name='ConsumoEnergia',
        ),
    ]
