# Generated by Django 5.1.4 on 2025-01-12 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casas', '0001_initial'),
        ('financeiro', '0002_rename_total_pago_financeiro_valor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='financeiro',
            old_name='data',
            new_name='data_fechamento',
        ),
        migrations.RenameField(
            model_name='financeiro',
            old_name='valor',
            new_name='pendencias',
        ),
        migrations.RemoveField(
            model_name='financeiro',
            name='descricao',
        ),
        migrations.AddField(
            model_name='financeiro',
            name='total_a_pagar',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='financeiro',
            name='total_pago',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='financeiro',
            name='casa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financeiro', to='casas.casa'),
        ),
    ]
