# Generated by Django 5.1.4 on 2025-01-12 17:23

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0003_rename_data_financeiro_data_fechamento_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='financeiro',
            old_name='total_a_pagar',
            new_name='total_alugueis',
        ),
        migrations.RemoveField(
            model_name='financeiro',
            name='data_fechamento',
        ),
        migrations.AddField(
            model_name='financeiro',
            name='total_despesas',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
