# Generated by Django 5.1.4 on 2025-01-12 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despesas', '0002_despesa_kw_final_despesa_kw_inicial_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesa',
            name='descricao',
            field=models.CharField(choices=[('Energia', 'Energia'), ('Água', 'Água')], max_length=50),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
