# Generated by Django 5.1.4 on 2025-01-12 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despesas', '0003_alter_despesa_descricao_alter_despesa_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesa',
            name='descricao',
            field=models.CharField(choices=[('Energia', 'Energia'), ('Agua', 'Água')], max_length=255),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='kw_final',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='kw_inicial',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='valor',
            field=models.FloatField(),
        ),
    ]
